services:

  iipsrv:
    image: camicroscope/iipimage:${ENV_IIPSRV_VERSION}
    container_name: iipsrv
    environment:
      VIRTUAL_HOST: iipsrv.local
    expose:
      - "80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./iipsrv/ports.conf:/etc/apache2/ports.conf
      - ./tiled-images:/mnt/images/
    networks:
      default:
        aliases:
          - iipsrv.local

  cantaloupe:
    image: uclalibrary/cantaloupe:${ENV_CANTALOUPE_VERSION}
    container_name: cantaloupe
    environment:
      CANTALOUPE_ENDPOINT_ADMIN_SECRET: foobar	# usr is admin
      CANTALOUPE_ENDPOINT_ADMIN_ENABLED: true
      VIRTUAL_HOST: cantaloupe.local
    ports:
      - "8182:8182"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./tiled-images:/imageroot
    networks:
      default:
        aliases:
          - cantaloupe.local

  mirador:
    build:
      context: mirador/
      args:
        - ENV_MIRADOR_VERSION
    container_name: mirador
    environment:
      VIRTUAL_HOST: viewer.local
      VIRTUAL_PORT: 4444
    volumes:
      - /etc/localtime:/etc/localtime:ro
