# Set CORS headers, so that live Javascript calls from omeka.local frontend to Solr endpoints on solr.local are not
# silently blocked by the browser.
# This is particularly relevant for the suggester endpoint that Advanced Search uses for autosuggest.
add_header Access-Control-Allow-Origin "http://omeka.local" always;
add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
